## roles/ansible-role-misc-tools/tasks/main.yml
# vim:ft=yaml.ansible:
---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Ensure misc. useful tools are installed
  package:
    name: '{{ misc_tools }}'
    state: present

...
